CREATE DATABASE IF NOT EXISTS ai_approval_system DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE ai_approval_system;

-- 用户表
CREATE TABLE IF NOT EXISTS `user` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL UNIQUE,
  `password` VARCHAR(100) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `role` VARCHAR(20) NOT NULL COMMENT '角色：admin, manager, employee',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 报销单表
CREATE TABLE IF NOT EXISTS `expense_claim` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `claim_date` DATE NOT NULL,
  `type` VARCHAR(50) NOT NULL COMMENT '报销类型：差旅费、办公费、餐饮费等',
  `description` TEXT,
  `status` VARCHAR(20) NOT NULL DEFAULT 'SUBMITTED' COMMENT '状态：SUBMITTED, PENDING, APPROVED, REJECTED',
  `ai_check_result` VARCHAR(255) COMMENT 'AI 检查结果',
  `ai_opinion` TEXT COMMENT 'AI 审批意见',
  `process_instance_id` VARCHAR(100) COMMENT 'Flowable 流程实例ID',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`user_id`) REFERENCES `user`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 报销明细项表
CREATE TABLE IF NOT EXISTS `expense_item` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `claim_id` BIGINT NOT NULL,
  `item_name` VARCHAR(100) NOT NULL,
  `item_amount` DECIMAL(10,2) NOT NULL,
  `item_date` DATE NOT NULL,
  `item_description` TEXT,
  FOREIGN KEY (`claim_id`) REFERENCES `expense_claim`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 审批记录表
CREATE TABLE IF NOT EXISTS `approval_record` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `claim_id` BIGINT NOT NULL,
  `approver_id` BIGINT NOT NULL,
  `approver_name` VARCHAR(50) NOT NULL,
  `approval_date` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `approval_status` VARCHAR(20) NOT NULL COMMENT '审批状态：APPROVED, REJECTED',
  `approval_opinion` TEXT,
  FOREIGN KEY (`claim_id`) REFERENCES `expense_claim`(`id`),
  FOREIGN KEY (`approver_id`) REFERENCES `user`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 初始化数据
INSERT INTO `user` (`username`, `password`, `name`, `role`) VALUES
('admin', '123456', '管理员', 'admin'),
('manager', '123456', '部门经理', 'manager'),
('employee', '123456', '普通员工', 'employee');

-- 角色权限表
CREATE TABLE IF NOT EXISTS `APP_MODEL_JSQX_ABCD` (
  `JA_UNID` BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
  `JA_UUID` VARCHAR(48) NOT NULL,
  `JA_CMM_USAGE_SCENARIOS` VARCHAR(128),
  `JA_CREATOR_DEPT_UUID` VARCHAR(48),
  `JA_CREATOR_DEPT_NAME` VARCHAR(128),
  `JA_CREATOR` VARCHAR(48),
  `JA_CREATOR_NAME` VARCHAR(128),
  `JA_CREATE_TIME` TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
  `JA_LAST_UPDATER` VARCHAR(48),
  `JA_LAST_UPDATER_NAME` VARCHAR(128),
  `JA_LAST_UPDATE_TIME` TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `JA_STATUS` VARCHAR(128) DEFAULT '1',
  `JA_ORDER` BIGINT(20) DEFAULT 0,
  `JA_MODELID` VARCHAR(128),
  `JA_TEXT` VARCHAR(128),
  `JA_CMM_FORM_UUID` VARCHAR(128),
  `JA_CMM_ENTITY_UUID` VARCHAR(128),
  `JA_CMM_GROUP_UUID` VARCHAR(128),
  `JA_ROLE_ID` VARCHAR(128) NOT NULL,
  `JA_ROLE_NAME` VARCHAR(128) NOT NULL,
  `JA_PERMISSION_ID` VARCHAR(128) NOT NULL,
  `JA_PERMISSION_NAME` VARCHAR(128) NOT NULL,
  `JA_PERMISSION_DESC` VARCHAR(255),
  `JA_MODULE` VARCHAR(128) NOT NULL,
  `JA_ACTION` VARCHAR(128) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 流程设置表
CREATE TABLE IF NOT EXISTS `APP_MODEL_LCSS_EFGH` (
  `LE_UNID` BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
  `LE_UUID` VARCHAR(48) NOT NULL,
  `LE_CMM_USAGE_SCENARIOS` VARCHAR(128),
  `LE_CREATOR_DEPT_UUID` VARCHAR(48),
  `LE_CREATOR_DEPT_NAME` VARCHAR(128),
  `LE_CREATOR` VARCHAR(48),
  `LE_CREATOR_NAME` VARCHAR(128),
  `LE_CREATE_TIME` TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
  `LE_LAST_UPDATER` VARCHAR(48),
  `LE_LAST_UPDATER_NAME` VARCHAR(128),
  `LE_LAST_UPDATE_TIME` TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `LE_STATUS` VARCHAR(128) DEFAULT '1',
  `LE_ORDER` BIGINT(20) DEFAULT 0,
  `LE_MODELID` VARCHAR(128),
  `LE_TEXT` VARCHAR(128),
  `LE_CMM_FORM_UUID` VARCHAR(128),
  `LE_CMM_ENTITY_UUID` VARCHAR(128),
  `LE_CMM_GROUP_UUID` VARCHAR(128),
  `LE_PROCESS_ID` VARCHAR(128) NOT NULL,
  `LE_PROCESS_NAME` VARCHAR(128) NOT NULL,
  `LE_STEP_ID` VARCHAR(128) NOT NULL,
  `LE_STEP_NAME` VARCHAR(128) NOT NULL,
  `LE_STEP_ORDER` BIGINT(20) NOT NULL,
  `LE_RESPONSIBLE_ROLE` VARCHAR(128) NOT NULL,
  `LE_DURATION` BIGINT(20) DEFAULT 24,
  `LE_CONDITION` VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 初始化角色权限数据
INSERT INTO `APP_MODEL_JSQX_ABCD` (`JA_UUID`, `JA_ROLE_ID`, `JA_ROLE_NAME`, `JA_PERMISSION_ID`, `JA_PERMISSION_NAME`, `JA_PERMISSION_DESC`, `JA_MODULE`, `JA_ACTION`)
VALUES
('1', 'admin', '管理员', 'submit', '提交报销', '允许提交报销单', '报销管理', 'submit'),
('2', 'admin', '管理员', 'approve', '审批报销', '允许审批报销单', '报销管理', 'approve'),
('3', 'admin', '管理员', 'manage_users', '管理用户', '允许管理用户', '用户管理', 'manage_users'),
('4', 'admin', '管理员', 'manage_roles', '管理角色', '允许管理角色权限', '用户管理', 'manage_roles'),
('5', 'manager', '部门经理', 'submit', '提交报销', '允许提交报销单', '报销管理', 'submit'),
('6', 'manager', '部门经理', 'approve', '审批报销', '允许审批报销单', '报销管理', 'approve'),
('7', 'employee', '普通员工', 'submit', '提交报销', '允许提交报销单', '报销管理', 'submit');

-- 初始化流程设置数据
INSERT INTO `APP_MODEL_LCSS_EFGH` (`LE_UUID`, `LE_PROCESS_ID`, `LE_PROCESS_NAME`, `LE_STEP_ID`, `LE_STEP_NAME`, `LE_STEP_ORDER`, `LE_RESPONSIBLE_ROLE`, `LE_DURATION`)
VALUES
('1', 'expenseApprovalProcess', '报销审批流程', 'manager_approval', '部门经理审批', 1, 'manager', 24),
('2', 'expenseApprovalProcess', '报销审批流程', 'finance_approval', '财务审批', 2, 'finance', 24);

-- 知识库表
CREATE TABLE IF NOT EXISTS `knowledge_base` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL COMMENT '文档名称',
  `description` TEXT COMMENT '文档描述',
  `document_path` VARCHAR(500) NOT NULL COMMENT '文档存储路径',
  `document_type` VARCHAR(100) COMMENT '文档类型',
  `file_size` BIGINT COMMENT '文件大小',
  `content` TEXT COMMENT '文档内容',
  `upload_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '上传时间',
  `vectorization_time` DATETIME COMMENT '向量化时间',
  `status` VARCHAR(50) DEFAULT 'UPLOADED' COMMENT '状态：UPLOADED, VECTORIZED, ERROR',
  `user_id` BIGINT COMMENT '上传用户ID',
  `tags` VARCHAR(255) COMMENT '文档标签，多个标签用逗号分隔',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 初始化流程定义表（由 Flowable 自动创建）